services:
  - type: web
    name: mem0-mcp-server
    env: python
    pythonVersion: "3.12.3"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn mcp_server:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /docs
    envVars:
      - key: OPENAI_API_KEY
        fromSync: false
